[project]
name = "contexta"
version = "0.1.0"
description = "RAG application"
authors = [
    {name = "Douglas Henrique",email = "douglas.hsp2019@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
