[project]
name = "contexta"
version = "0.1.0"
description = "RAG application"
authors = [
    {name = "Douglas Henrique",email = "douglas.hsp2019@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.128.0,<0.129.0)",
    "uvicorn (>=0.40.0,<0.41.0)",
    "django (>=6.0.1,<7.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "pypdf (>=5.0.0,<6.0.0)",
    "openai (>=1.0.0,<2.0.0)",
    "qdrant-client (>=1.7.0,<2.0.0)",
    "djangorestframework (>=3.15.0,<4.0.0)",
    "httpx (>=0.27.0,<1.0.0)",
    "python-docx (>=1.1.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
